
@startuml

class ChessGame {
    - board: ChessBoard
    - currentPlayer: Player
    - gameOver: boolean
    + start(): void
    + movePiece(from: Square, to: Square): Move
    + isCheckmate(): boolean
    + isStalemate(): boolean
}

class ChessBoard {
    - squares: Square[8][8]
        - pieceFactory: ChessPieceFactory
    + initialize(): void
    + movePiece(from: Square, to: Square): boolean
    + isSquareOccupied(square: Square): boolean
    + isEnPassantSquare(square: Square): boolean
    + isCastlingMove(from: Square, to: Square): boolean
    + isPromotionMove(from: Square, to: Square): boolean
    + performEnPassantCapture(from: Square, to: Square): void
    + performCastlingMove(from: Square, to: Square): void
    + performPromotionMove(from: Square, to: Square, promotionPiece: Piece): void
    + executeMove(move: Move): boolean
    + isCheck(): boolean
    + isCheckmate(): boolean
    + isStalemate(): boolean
}

class Square {
    - file: File
    - rank: Rank
    + getFile(): File
    + getRank(): Rank
    + equals(square: Square): boolean
}

enum Color {
    WHITE
    BLACK
}

enum File {
    A, B, C, D, E, F, G, H
}

enum Rank {
    1, 2, 3, 4, 5, 6, 7, 8
}

abstract class Piece {
    - color: Color
    - hasMoved: boolean
    - strategy: ChessPieceStrategy
    + getColor(): Color
    + hasMoved(): boolean
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
}

class Pawn {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
    + canPerformEnPassant(from: Square, to: Square): boolean
}

class Rook {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
}

class Knight {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
}

class Bishop {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
}

class Queen {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
}

class King {
    + canMoveTo(square: Square): boolean
    + moveTo(square: Square): boolean
    + canPerformCastling(from: Square, to: Square): boolean
}

class Player {
    - color: Color
    - capturedPieces: Piece[]
    + makeMove(board: ChessBoard, from: Square, to: Square): Move
}

class Move {
    - piece: Piece
    - fromSquare: Square
    - toSquare: Square
    - isCapture: boolean
    + execute(): void
    + undo(): void
}

interface ChessPieceFactory {
    + createPiece(pieceType: PieceType, color: Color): Piece
}

class ChessPieceFactoryImpl implements ChessPieceFactory {
    + createPiece(pieceType: PieceType, color: Color): Piece
}

enum PieceType {
    PAWN, ROOK, KNIGHT, BISHOP, QUEEN, KING
}

interface ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}


class PawnStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}

class RookStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}

class KnightStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}

class BishopStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}

class QueenStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}

class KingStrategy implements ChessPieceStrategy {
    + canMoveTo(square: Square, board: ChessBoard): boolean
}
        
ChessGame --> ChessBoard
ChessGame --> Player
ChessBoard --> Square
ChessBoard --> Piece
ChessBoard --> ChessPieceFactory
ChessBoard --> ChessPieceStrategy
Piece --> ChessPieceStrategy
Piece --> Move
Player --> ChessBoard
Piece <|-- Pawn
Piece <|-- Rook
Piece <|-- Knight
Piece <|-- Bishop
Piece <|-- Queen
Piece <|-- King
Pawn --> PawnStrategy
Rook --> RookStrategy
Knight --> KnightStrategy
Bishop --> BishopStrategy
Queen --> QueenStrategy
King --> KingStrategy
Piece o--> ChessPieceStrategy
Piece o--> Move

Player "1" *-- "*" Piece

@enduml
